function soilK = soilThermalCon(kSolid, kWater,...
                                thetaIce, thetaWater, thetaSoild, thetaAir)

kIce = 2.29;   % ice thermal conductivity
kAir = 0.025;  % air thermal conductivity

soilK = kIce ^ thetaIce * ...
    kSolid ^ thetaSoild * ...
    kWater ^ thetaWater * ...
    kAir ^ thetaAir;
                        
end